vf_shader(ps_vw_depth vw_linear_depth.hlsl ps_3_0 /DPACKED_DEPTH=0)
vf_shader(ps_vw_depth_packed vw_linear_depth.hlsl ps_3_0 /DPACKED_DEPTH=1)
vf_shader(ps_vw_shade_low vw_water.hlsl ps_3_0 /DSSR_STEPS=0)
vf_shader(ps_vw_shade_mid vw_water.hlsl ps_3_0 /DSSR_STEPS=8)
vf_shader(ps_vw_shade_high vw_water.hlsl ps_3_0 /DSSR_STEPS=16)
vf_shader(ps_vw_ripple_step vw_ripple_step.hlsl ps_3_0)
