vf_shader(ps_vw_fft_evolve vw_fft_evolve.hlsl ps_3_0)
vf_shader(ps_vw_fft_rows vw_fft_butterfly.hlsl ps_3_0 /DCOLUMNS=0 /DFUSED_STAGES=0 /DASSEMBLE=0)
vf_shader(ps_vw_fft_rows_fused vw_fft_butterfly.hlsl ps_3_0 /DCOLUMNS=0 /DFUSED_STAGES=1 /DASSEMBLE=0)
vf_shader(ps_vw_fft_columns vw_fft_butterfly.hlsl ps_3_0 /DCOLUMNS=1 /DFUSED_STAGES=0 /DASSEMBLE=0)
vf_shader(ps_vw_fft_columns_fused vw_fft_butterfly.hlsl ps_3_0 /DCOLUMNS=1 /DFUSED_STAGES=1 /DASSEMBLE=0)
vf_shader(ps_vw_fft_assemble_fused vw_fft_butterfly.hlsl ps_3_0 /DCOLUMNS=1 /DFUSED_STAGES=1 /DASSEMBLE=1)
vf_shader(ps_vw_fft_surface_foam vw_fft_surface.hlsl ps_3_0 /DSURFACE=1 /DFOAM=1)
vf_shader(ps_vw_fft_surface vw_fft_surface.hlsl ps_3_0 /DSURFACE=1 /DFOAM=0)
vf_shader(ps_vw_fft_foam vw_fft_surface.hlsl ps_3_0 /DSURFACE=0 /DFOAM=1)
vf_shader(ps_vw_fft_mip vw_fft_mip.hlsl ps_3_0 /DPAIRED=0)
vf_shader(ps_vw_fft_mip_pair vw_fft_mip.hlsl ps_3_0 /DPAIRED=1)
